### ISSUE TITLE
Nav Item contrast

### ISSUE THREAD

**Issue by brnt-toast** [JohnReid/JohnReid.github.io#1]
each page listed in the nav bar inside the header are hard to read due to not enough contrast. Adding a filter of 75% contrast in the header partial fixes this. If interested a PR can be submitted.

**Comment by JohnReid** [comment]
Hi @brnt-toast thanks for your interest in my web site. CSS is certainly not my thing so I'm always happy to see how it should be done. A PR would be great. Thanks!
